#!/usr/bin/env node

/**
 * Development Multi-Agent System
 *
 * Các agents chuyên biệt cho phát triển:
 * - Testing Agent: Tạo và chạy tests
 * - Refactoring Agent: Cải thiện code quality
 * - Documentation Agent: Tạo/cập nhật docs
 * - Optimization Agent: Tối ưu performance
 * - Security Agent: Scan security issues
 * - Code Review Agent: Review code changes
 */

const fs = require("fs");
const path = require("path");
const { execSync, spawn } = require("child_process");

/**
 * Base Development Agent
 */
class DevAgent {
  constructor(name, task) {
    this.name = name;
    this.task = task;
    this.status = "pending";
    this.result = null;
    this.error = null;
    this.startTime = null;
    this.endTime = null;
    this.logs = [];
  }

  log(message) {
    const timestamp = new Date().toISOString();
    this.logs.push({ timestamp, message });
    console.log(`[${this.name}] ${message}`);
  }

  async execute() {
    this.status = "running";
    this.startTime = Date.now();
    this.log("Starting...");

    try {
      this.result = await this.task();
      this.status = "completed";
      this.endTime = Date.now();
      this.log(`Completed in ${this.duration()}ms`);
      return this.result;
    } catch (error) {
      this.status = "failed";
      this.error = error;
      this.endTime = Date.now();
      this.log(`Failed: ${error.message}`);
      throw error;
    }
  }

  duration() {
    return this.endTime - this.startTime;
  }

  getReport() {
    return {
      name: this.name,
      status: this.status,
      duration: this.duration(),
      result: this.result,
      error: this.error?.message,
      logs: this.logs
    };
  }
}

/**
 * Testing Agent
 * Tạo và chạy unit tests, integration tests
 */
class TestingAgent extends DevAgent {
  constructor(targetFiles = []) {
    super("TestingAgent", async () => {
      const results = {
        testsCreated: [],
        testsRun: [],
        coverage: null,
        passed: 0,
        failed: 0
      };

      // Tìm files cần test
      const filesToTest = targetFiles.length > 0
        ? targetFiles
        : this.findFilesNeedingTests();

      this.log(`Found ${filesToTest.length} files needing tests`);

      // Tạo tests cho từng file
      for (const file of filesToTest) {
        try {
          const testFile = await this.createTestFile(file);
          results.testsCreated.push(testFile);
          this.log(`Created test: ${testFile}`);
        } catch (error) {
          this.log(`Failed to create test for ${file}: ${error.message}`);
        }
      }

      // Chạy tests
      try {
        const testResults = await this.runTests();
        results.testsRun = testResults.tests;
        results.passed = testResults.passed;
        results.failed = testResults.failed;
        results.coverage = testResults.coverage;
      } catch (error) {
        this.log(`Test execution failed: ${error.message}`);
      }

      return results;
    });
    this.targetFiles = targetFiles;
  }

  findFilesNeedingTests() {
    const files = [];
    const jsFiles = this.findJSFiles(".");

    for (const file of jsFiles) {
      const testFile = file.replace(/\.js$/, ".test.js");
      if (!fs.existsSync(testFile)) {
        files.push(file);
      }
    }

    return files.slice(0, 5); // Limit to 5 files
  }

  findJSFiles(dir) {
    const files = [];
    const entries = fs.readdirSync(dir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        if (!["node_modules", ".git", "lessons"].includes(entry.name)) {
          files.push(...this.findJSFiles(fullPath));
        }
      } else if (entry.name.endsWith(".js") && !entry.name.endsWith(".test.js")) {
        files.push(fullPath);
      }
    }

    return files;
  }

  async createTestFile(sourceFile) {
    const testFile = sourceFile.replace(/\.js$/, ".test.js");
    const moduleName = path.basename(sourceFile, ".js");

    const testTemplate = `
/**
 * Tests for ${moduleName}
 * Auto-generated by TestingAgent
 */

const ${moduleName} = require('./${moduleName}');

describe('${moduleName}', () => {
  test('should be defined', () => {
    expect(${moduleName}).toBeDefined();
  });

  // TODO: Add more tests
});
`;

    fs.writeFileSync(testFile, testTemplate.trim(), "utf8");
    return testFile;
  }

  async runTests() {
    // Placeholder - would integrate with Jest/Mocha
    return {
      tests: ["test1", "test2"],
      passed: 2,
      failed: 0,
      coverage: "85%"
    };
  }
}

/**
 * Refactoring Agent
 * Cải thiện code quality, remove duplicates, optimize
 */
class RefactoringAgent extends DevAgent {
  constructor(targetFiles = []) {
    super("RefactoringAgent", async () => {
      const results = {
        filesAnalyzed: 0,
        issuesFound: [],
        refactorings: [],
        improvements: []
      };

      const files = targetFiles.length > 0
        ? targetFiles
        : this.findFilesToRefactor();

      this.log(`Analyzing ${files.length} files...`);

      for (const file of files) {
        try {
          const analysis = await this.analyzeFile(file);
          results.filesAnalyzed++;
          results.issuesFound.push(...analysis.issues);

          if (analysis.canRefactor) {
            const refactored = await this.refactorFile(file, analysis);
            results.refactorings.push(refactored);
            this.log(`Refactored: ${file}`);
          }
        } catch (error) {
          this.log(`Failed to refactor ${file}: ${error.message}`);
        }
      }

      return results;
    });
    this.targetFiles = targetFiles;
  }

  findFilesToRefactor() {
    // Find files with potential issues
    const files = [];
    const jsFiles = fs.readdirSync(".")
      .filter(f => f.endsWith(".js") && !f.includes("test"));

    return jsFiles.slice(0, 3); // Limit to 3 files
  }

  async analyzeFile(file) {
    const content = fs.readFileSync(file, "utf8");
    const issues = [];

    // Check for long functions
    const functionMatches = content.match(/function\s+\w+\s*\([^)]*\)\s*{/g) || [];
    if (functionMatches.length > 10) {
      issues.push({ type: "complexity", message: "Too many functions" });
    }

    // Check for magic numbers
    const numberMatches = content.match(/\b\d+\.\d+\b/g) || [];
    if (numberMatches.length > 5) {
      issues.push({ type: "magic-numbers", message: "Magic numbers found" });
    }

    // Check for duplicated code
    const lines = content.split("\n");
    const duplicates = this.findDuplicateLines(lines);
    if (duplicates.length > 0) {
      issues.push({ type: "duplication", message: `${duplicates.length} duplicate blocks` });
    }

    return {
      file,
      issues,
      canRefactor: issues.length > 0,
      suggestions: this.generateSuggestions(issues)
    };
  }

  findDuplicateLines(lines) {
    const seen = new Map();
    const duplicates = [];

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();
      if (line.length > 20) {
        if (seen.has(line)) {
          duplicates.push({ line: i, duplicate: seen.get(line) });
        } else {
          seen.set(line, i);
        }
      }
    }

    return duplicates;
  }

  generateSuggestions(issues) {
    return issues.map(issue => {
      switch (issue.type) {
        case "complexity":
          return "Consider splitting into smaller functions";
        case "magic-numbers":
          return "Extract magic numbers to named constants";
        case "duplication":
          return "Extract duplicated code to shared functions";
        default:
          return "Review and improve";
      }
    });
  }

  async refactorFile(file, analysis) {
    // Placeholder - would apply actual refactorings
    return {
      file,
      changes: analysis.suggestions,
      status: "analyzed"
    };
  }
}

/**
 * Documentation Agent
 * Tạo và cập nhật documentation
 */
class DocumentationAgent extends DevAgent {
  constructor(scope = "all") {
    super("DocumentationAgent", async () => {
      const results = {
        filesDocumented: [],
        docsCreated: [],
        docsUpdated: []
      };

      // Analyze codebase
      const analysis = await this.analyzeCodebase();
      this.log(`Found ${analysis.undocumented.length} undocumented items`);

      // Generate API docs
      if (scope === "all" || scope === "api") {
        const apiDocs = await this.generateAPIDocs(analysis);
        results.docsCreated.push(apiDocs);
        this.log("Generated API documentation");
      }

      // Generate README sections
      if (scope === "all" || scope === "readme") {
        const readme = await this.updateREADME(analysis);
        results.docsUpdated.push(readme);
        this.log("Updated README.md");
      }

      // Generate JSDoc comments
      if (scope === "all" || scope === "jsdoc") {
        const jsdocs = await this.generateJSDocs(analysis);
        results.filesDocumented.push(...jsdocs);
        this.log(`Added JSDoc to ${jsdocs.length} files`);
      }

      return results;
    });
    this.scope = scope;
  }

  async analyzeCodebase() {
    const files = fs.readdirSync(".")
      .filter(f => f.endsWith(".js") && !f.includes("test"));

    const undocumented = [];
    const functions = [];

    for (const file of files) {
      const content = fs.readFileSync(file, "utf8");

      // Find functions without JSDoc
      const functionRegex = /(?:^|\n)(?!\/\*\*).*?function\s+(\w+)/g;
      let match;
      while ((match = functionRegex.exec(content)) !== null) {
        undocumented.push({ file, function: match[1] });
        functions.push({ file, name: match[1] });
      }
    }

    return { undocumented, functions, files };
  }

  async generateAPIDocs(analysis) {
    const apiDoc = `# API Documentation

## Functions

${analysis.functions.map(f => `
### ${f.name}

**File:** \`${f.file}\`

**Description:** TODO: Add description

**Parameters:** TODO: Add parameters

**Returns:** TODO: Add return type

**Example:**
\`\`\`javascript
// TODO: Add example
\`\`\`
`).join("\n")}

---
*Auto-generated by DocumentationAgent on ${new Date().toISOString()}*
`;

    const docPath = "API_DOCS.md";
    fs.writeFileSync(docPath, apiDoc, "utf8");
    return docPath;
  }

  async updateREADME(analysis) {
    const readmePath = "README.md";
    let readme = fs.existsSync(readmePath)
      ? fs.readFileSync(readmePath, "utf8")
      : "# Project\n\n";

    // Add API reference section if not exists
    if (!readme.includes("## API Reference")) {
      readme += `\n## API Reference\n\nSee [API_DOCS.md](API_DOCS.md) for detailed API documentation.\n`;
    }

    fs.writeFileSync(readmePath, readme, "utf8");
    return readmePath;
  }

  async generateJSDocs(analysis) {
    const documented = [];

    for (const item of analysis.undocumented.slice(0, 5)) {
      try {
        const content = fs.readFileSync(item.file, "utf8");
        const jsdoc = `/**
 * ${item.function}
 * @param {*} params - Parameters
 * @returns {*} Result
 */`;

        // Insert JSDoc before function
        const updated = content.replace(
          new RegExp(`function\\s+${item.function}`),
          `${jsdoc}\nfunction ${item.function}`
        );

        fs.writeFileSync(item.file, updated, "utf8");
        documented.push(item.file);
      } catch (error) {
        this.log(`Failed to document ${item.file}: ${error.message}`);
      }
    }

    return documented;
  }
}

/**
 * Optimization Agent
 * Tối ưu performance, bundle size, memory usage
 */
class OptimizationAgent extends DevAgent {
  constructor() {
    super("OptimizationAgent", async () => {
      const results = {
        analyzed: [],
        optimizations: [],
        metrics: {}
      };

      // Analyze bundle size
      const bundleAnalysis = await this.analyzeBundleSize();
      results.analyzed.push("bundle-size");
      results.metrics.bundleSize = bundleAnalysis;

      // Find performance bottlenecks
      const perfIssues = await this.findPerformanceIssues();
      results.analyzed.push("performance");
      results.optimizations.push(...perfIssues);

      // Optimize images
      const imageOpt = await this.optimizeImages();
      results.analyzed.push("images");
      results.metrics.imagesOptimized = imageOpt.count;

      // Memory leak detection
      const memoryIssues = await this.detectMemoryLeaks();
      results.analyzed.push("memory");
      results.optimizations.push(...memoryIssues);

      return results;
    });
  }

  async analyzeBundleSize() {
    const packageJson = JSON.parse(fs.readFileSync("package.json", "utf8"));
    const dependencies = Object.keys(packageJson.dependencies || {});

    return {
      dependencies: dependencies.length,
      recommendation: dependencies.length > 20
        ? "Consider reducing dependencies"
        : "Bundle size looks good"
    };
  }

  async findPerformanceIssues() {
    const issues = [];
    const files = fs.readdirSync(".").filter(f => f.endsWith(".js"));

    for (const file of files) {
      const content = fs.readFileSync(file, "utf8");

      // Check for synchronous operations
      if (content.includes("Sync(")) {
        issues.push({
          file,
          type: "sync-operation",
          suggestion: "Use async alternatives"
        });
      }

      // Check for nested loops
      const nestedLoops = (content.match(/for\s*\([^)]*\)\s*{[^}]*for\s*\(/g) || []).length;
      if (nestedLoops > 0) {
        issues.push({
          file,
          type: "nested-loops",
          suggestion: "Consider optimizing nested loops"
        });
      }
    }

    return issues;
  }

  async optimizeImages() {
    // Placeholder - would use image optimization tools
    return { count: 0, savedBytes: 0 };
  }

  async detectMemoryLeaks() {
    const issues = [];
    const files = fs.readdirSync(".").filter(f => f.endsWith(".js"));

    for (const file of files) {
      const content = fs.readFileSync(file, "utf8");

      // Check for event listeners without cleanup
      if (content.includes("addEventListener") && !content.includes("removeEventListener")) {
        issues.push({
          file,
          type: "memory-leak",
          suggestion: "Add removeEventListener in cleanup"
        });
      }

      // Check for timers without cleanup
      if (content.includes("setInterval") && !content.includes("clearInterval")) {
        issues.push({
          file,
          type: "memory-leak",
          suggestion: "Clear intervals in cleanup"
        });
      }
    }

    return issues;
  }
}

/**
 * Security Agent
 * Scan security vulnerabilities
 */
class SecurityAgent extends DevAgent {
  constructor() {
    super("SecurityAgent", async () => {
      const results = {
        vulnerabilities: [],
        dependencies: [],
        codeIssues: [],
        severity: "low"
      };

      // Check dependencies
      const depVulns = await this.checkDependencies();
      results.dependencies = depVulns;

      // Scan code for security issues
      const codeIssues = await this.scanCode();
      results.codeIssues = codeIssues;

      // Check for exposed secrets
      const secrets = await this.findExposedSecrets();
      results.vulnerabilities.push(...secrets);

      // Determine severity
      results.severity = this.calculateSeverity(results);

      return results;
    });
  }

  async checkDependencies() {
    // Placeholder - would use npm audit
    return [];
  }

  async scanCode() {
    const issues = [];
    const files = fs.readdirSync(".").filter(f => f.endsWith(".js"));

    for (const file of files) {
      const content = fs.readFileSync(file, "utf8");

      // Check for eval()
      if (content.includes("eval(")) {
        issues.push({
          file,
          type: "dangerous-function",
          severity: "high",
          message: "Use of eval() detected"
        });
      }

      // Check for SQL injection
      if (content.match(/query\s*\([^)]*\+[^)]*\)/)) {
        issues.push({
          file,
          type: "sql-injection",
          severity: "critical",
          message: "Potential SQL injection"
        });
      }

      // Check for XSS
      if (content.includes("innerHTML") && !content.includes("sanitize")) {
        issues.push({
          file,
          type: "xss",
          severity: "high",
          message: "Potential XSS vulnerability"
        });
      }
    }

    return issues;
  }

  async findExposedSecrets() {
    const secrets = [];
    const files = fs.readdirSync(".").filter(f => f.endsWith(".js") || f.endsWith(".json"));

    for (const file of files) {
      const content = fs.readFileSync(file, "utf8");

      // Check for API keys
      if (content.match(/[A-Za-z0-9]{32,}/)) {
        secrets.push({
          file,
          type: "potential-secret",
          severity: "medium",
          message: "Potential API key or secret found"
        });
      }
    }

    return secrets;
  }

  calculateSeverity(results) {
    const hasCritical = results.codeIssues.some(i => i.severity === "critical");
    const hasHigh = results.codeIssues.some(i => i.severity === "high");

    if (hasCritical) return "critical";
    if (hasHigh) return "high";
    if (results.codeIssues.length > 0) return "medium";
    return "low";
  }
}

/**
 * Code Review Agent
 * Review code changes and provide feedback
 */
class CodeReviewAgent extends DevAgent {
  constructor(files = []) {
    super("CodeReviewAgent", async () => {
      const results = {
        filesReviewed: 0,
        issues: [],
        suggestions: [],
        score: 0
      };

      const filesToReview = files.length > 0
        ? files
        : this.getChangedFiles();

      this.log(`Reviewing ${filesToReview.length} files...`);

      for (const file of filesToReview) {
        const review = await this.reviewFile(file);
        results.filesReviewed++;
        results.issues.push(...review.issues);
        results.suggestions.push(...review.suggestions);
      }

      results.score = this.calculateScore(results);

      return results;
    });
    this.files = files;
  }

  getChangedFiles() {
    try {
      const output = execSync("git diff --name-only HEAD", { encoding: "utf8" });
      return output.split("\n").filter(f => f.endsWith(".js"));
    } catch {
      return [];
    }
  }

  async reviewFile(file) {
    const content = fs.readFileSync(file, "utf8");
    const issues = [];
    const suggestions = [];

    // Check code style
    if (!content.includes("'use strict'") && !content.includes('"use strict"')) {
      suggestions.push({
        file,
        type: "style",
        message: "Consider adding 'use strict'"
      });
    }

    // Check for console.log
    const consoleLogs = (content.match(/console\.log/g) || []).length;
    if (consoleLogs > 5) {
      issues.push({
        file,
        type: "debugging",
        message: `Found ${consoleLogs} console.log statements`
      });
    }

    // Check for TODO comments
    const todos = (content.match(/\/\/\s*TODO/g) || []).length;
    if (todos > 0) {
      suggestions.push({
        file,
        type: "todo",
        message: `${todos} TODO comments found`
      });
    }

    return { issues, suggestions };
  }

  calculateScore(results) {
    let score = 100;
    score -= results.issues.length * 5;
    score -= results.suggestions.length * 2;
    return Math.max(0, score);
  }
}

/**
 * Development Orchestrator
 */
class DevOrchestrator {
  constructor() {
    this.agents = [];
  }

  addAgent(agent) {
    this.agents.push(agent);
  }

  async executeAll() {
    console.log(`\n🤖 Executing ${this.agents.length} development agents...\n`);

    const results = [];

    for (const agent of this.agents) {
      try {
        const result = await agent.execute();
        results.push(agent.getReport());
      } catch (error) {
        console.error(`❌ ${agent.name} failed:`, error.message);
        results.push(agent.getReport());
      }
    }

    this.printSummary(results);
    return results;
  }

  async executeParallel() {
    console.log(`\n🤖 Executing ${this.agents.length} agents in parallel...\n`);

    const promises = this.agents.map(agent => agent.execute().catch(e => e));
    await Promise.all(promises);

    const results = this.agents.map(a => a.getReport());
    this.printSummary(results);
    return results;
  }

  printSummary(results) {
    console.log("\n" + "=".repeat(60));
    console.log("📊 DEVELOPMENT AGENTS SUMMARY");
    console.log("=".repeat(60));

    results.forEach(result => {
      const status = result.status === "completed" ? "✅" : "❌";
      const duration = result.duration ? `${result.duration}ms` : "N/A";
      console.log(`${status} ${result.name.padEnd(25)} ${duration.padStart(10)}`);
    });

    console.log("=".repeat(60) + "\n");
  }
}

// CLI
if (require.main === module) {
  const command = process.argv[2];

  async function main() {
    const orchestrator = new DevOrchestrator();

    switch (command) {
      case "test":
        orchestrator.addAgent(new TestingAgent());
        break;

      case "refactor":
        orchestrator.addAgent(new RefactoringAgent());
        break;

      case "docs":
        orchestrator.addAgent(new DocumentationAgent());
        break;

      case "optimize":
        orchestrator.addAgent(new OptimizationAgent());
        break;

      case "security":
        orchestrator.addAgent(new SecurityAgent());
        break;

      case "review":
        orchestrator.addAgent(new CodeReviewAgent());
        break;

      case "all":
        orchestrator.addAgent(new TestingAgent());
        orchestrator.addAgent(new RefactoringAgent());
        orchestrator.addAgent(new DocumentationAgent());
        orchestrator.addAgent(new OptimizationAgent());
        orchestrator.addAgent(new SecurityAgent());
        orchestrator.addAgent(new CodeReviewAgent());
        break;

      default:
        console.log("Usage: node dev_agents.js <command>");
        console.log("\nCommands:");
        console.log("  test      - Run testing agent");
        console.log("  refactor  - Run refactoring agent");
        console.log("  docs      - Run documentation agent");
        console.log("  optimize  - Run optimization agent");
        console.log("  security  - Run security agent");
        console.log("  review    - Run code review agent");
        console.log("  all       - Run all agents");
        process.exit(1);
    }

    await orchestrator.executeAll();
  }

  main().catch(error => {
    console.error("Fatal error:", error);
    process.exit(1);
  });
}

module.exports = {
  TestingAgent,
  RefactoringAgent,
  DocumentationAgent,
  OptimizationAgent,
  SecurityAgent,
  CodeReviewAgent,
  DevOrchestrator
};
